In [3]:
import sys
import pandas as pd
import numpy as np
import sklearn

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)

print("\nEntorno listo para Machine Learning.")

Python: 3.13.13 | packaged by Anaconda, Inc. | (main, Apr 22 2026, 16:49:16) [MSC v.1938 64 bit (AMD64)]
Pandas: 3.0.0
NumPy: 2.3.5
Scikit-learn: 1.8.0

Entorno listo para Machine Learning.

In [4]:
archivo = r"C:\Users\perey\OneDrive - Esri Colombia, Ecuador y Panamá\Esmeraldina\Fase IV. Machine Learning\Esmeraldina-ArcGISPro\CSV'S\Dataset_Simulacion_Esmeraldina_FaseIII_Calificado.csv"

df = pd.read_csv(archivo, sep=";")

print("CSV cargado correctamente.")
print("Número de muestras:", df.shape[0])
print("Número de columnas:", df.shape[1])

df.head()

CSV cargado correctamente.
Número de muestras: 300
Número de columnas: 37

,ID_MUESTRA,LATITUD,LONGITUD,PROFUNDIDAD_m,UNIDAD_ESTRATIGRAFICA,LITOLOGIA,DIST_FALLA_m,DIST_INTERSECCION_m,GUIA_PIRITA,Na_pct,...,APORTE_LITOLOGIA,APORTE_Na,APORTE_K,APORTE_Cr,APORTE_V,APORTE_K_Na,APORTE_Be,APORTE_GUIA_PIRITA,IPE,CATEGORIA_IPE
0,MUZO_001,5.486321,-74.055546,71.4,Formacion_Rosa_Blanca,Micrita,77.4,85.4,Alta,53.941,...,12.0,8.0,0.0,0,0,2.4,0.0,3.0,53.4,Moderado
1,MUZO_002,5.509561,-74.045010,167.3,Formacion_Furatena,Limolita micacea,55.7,323.6,Alta,88.208,...,3.0,8.0,0.0,0,0,4.8,0.0,3.0,40.8,Moderado
2,MUZO_003,5.577196,-74.025458,50.1,Formacion_Furatena,Limolita micacea,8.8,123.0,Baja,2.525,...,3.0,4.0,0.0,0,0,0.0,0.0,0.9,36.9,Bajo
3,MUZO_004,5.470668,-74.040809,10.1,Formacion_Rosa_Blanca,Micrita,68.9,96.3,Media,29.411,...,12.0,8.0,0.0,0,0,3.2,0.0,1.8,53.0,Moderado
4,MUZO_005,5.517515,-74.135338,98.8,Formacion_Rosa_Blanca,Lodolita oscura,305.4,35.2,Media,89.181,...,12.0,8.0,0.0,9,8,1.6,0.0,1.8,65.9,Alto

In [5]:
print("COLUMNAS DEL DATASET:\n")

for i, columna in enumerate(df.columns, start=1):
    print(i, "-", columna)

COLUMNAS DEL DATASET:

1 - ID_MUESTRA
2 - LATITUD
3 - LONGITUD
4 - PROFUNDIDAD_m
5 - UNIDAD_ESTRATIGRAFICA
6 - LITOLOGIA
7 - DIST_FALLA_m
8 - DIST_INTERSECCION_m
9 - GUIA_PIRITA
10 - Na_pct
11 - K_pct
12 - CR_ppm
13 - V_ppm
14 - K_Na
15 - Be_ppm
16 - SCORE_DIST_INTERSECCION
17 - SCORE_DIST_FALLA
18 - SCORE_LITOLOGIA
19 - SCORE_Na
20 - SCORE_K
21 - SCORE_Cr
22 - SCORE_V
23 - SCORE_K_Na
24 - SCORE_Be
25 - SCORE_GUIA_PIRITA
26 - APORTE_DIST_INTERSECCION
27 - APORTE_DIST_FALLA
28 - APORTE_LITOLOGIA
29 - APORTE_Na
30 - APORTE_K
31 - APORTE_Cr
32 - APORTE_V
33 - APORTE_K_Na
34 - APORTE_Be
35 - APORTE_GUIA_PIRITA
36 - IPE
37 - CATEGORIA_IPE

In [6]:
# Variables explicativas
columnas_X = [
    "LITOLOGIA",
    "DIST_FALLA_m",
    "DIST_INTERSECCION_m",
    "GUIA_PIRITA",
    "Na_pct",
    "K_pct",
    "CR_ppm",
    "V_ppm",
    "K_Na",
    "Be_ppm"
]

# X = información que utilizará el modelo
X = df[columnas_X].copy()

# y = valor que queremos que el modelo aprenda a predecir
y = df["IPE"].copy()

print("Dimensiones de X:", X.shape)
print("Dimensiones de y:", y.shape)

print("\nPrimeras filas de X:")
display(X.head())

print("\nPrimeros valores de y:")
display(y.head())

Dimensiones de X: (300, 10)
Dimensiones de y: (300,)

Primeras filas de X:

,LITOLOGIA,DIST_FALLA_m,DIST_INTERSECCION_m,GUIA_PIRITA,Na_pct,K_pct,CR_ppm,V_ppm,K_Na,Be_ppm
0,Micrita,77.4,85.4,Alta,53.941,43.562,2006.23,2447.56,0.808,388.02
1,Limolita micacea,55.7,323.6,Alta,88.208,44.627,3777.04,3242.05,0.506,438.00
2,Limolita micacea,8.8,123.0,Baja,2.525,50.871,951.31,4800.23,20.147,333.67
3,Micrita,68.9,96.3,Media,29.411,23.014,3025.11,1967.30,0.782,757.74
4,Lodolita oscura,305.4,35.2,Media,89.181,87.360,59.95,186.47,0.980,7.51

Primeros valores de y:

0    53.4
1    40.8
2    36.9
3    53.0
4    65.9
Name: IPE, dtype: float64

In [7]:
print("TIPOS DE DATOS DE X:\n")
print(X.dtypes)

print("\nTIPO DE DATO DE y:")
print(y.dtype)

TIPOS DE DATOS DE X:

LITOLOGIA                  str
DIST_FALLA_m           float64
DIST_INTERSECCION_m    float64
GUIA_PIRITA                str
Na_pct                 float64
K_pct                  float64
CR_ppm                 float64
V_ppm                  float64
K_Na                   float64
Be_ppm                 float64
dtype: object

TIPO DE DATO DE y:
float64

In [8]:
print("VALORES ÚNICOS DE GUIA_PIRITA:")
print(X["GUIA_PIRITA"].unique())

print("\nVALORES ÚNICOS DE LITOLOGIA:")
print(X["LITOLOGIA"].unique())

VALORES ÚNICOS DE GUIA_PIRITA:
<ArrowStringArray>
['Alta', 'Baja', 'Media', 'Ausente']
Length: 4, dtype: str

VALORES ÚNICOS DE LITOLOGIA:
<ArrowStringArray>
[                          'Micrita',                  'Limolita micacea',
                   'Lodolita oscura',                             'Shale',
 'Brecha hidrotermal calcita-pirita',                'Caliza bioclastica',
                       'Arcillolita',                      'Lutita negra',
                'Lodolita carbonosa',               'Lodolita albitizada',
            'Arcillolita con pirita',                     'Micrita negra',
                     'Cuarzoarenita',                 'Lodolita calcarea',
                  'Caliza micritica']
Length: 15, dtype: str

In [9]:
import sklearn

print("Scikit-learn instalado correctamente.")
print("Versión:", sklearn.__version__)

Scikit-learn instalado correctamente.
Versión: 1.8.0

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=2026
)

print("DATOS DE ENTRENAMIENTO")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nDATOS DE PRUEBA")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

DATOS DE ENTRENAMIENTO
X_train: (240, 10)
y_train: (240,)

DATOS DE PRUEBA
X_test: (60, 10)
y_test: (60,)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

# Variable categórica sin orden
variable_litologia = ["LITOLOGIA"]

# Variable categórica con orden
variable_pirita = ["GUIA_PIRITA"]

# Variables que ya son numéricas
variables_numericas = [
    "DIST_FALLA_m",
    "DIST_INTERSECCION_m",
    "Na_pct",
    "K_pct",
    "CR_ppm",
    "V_ppm",
    "K_Na",
    "Be_ppm"
]

# Codificación ordenada de la guía de pirita
codificador_pirita = OrdinalEncoder(
    categories=[["Ausente", "Baja", "Media", "Alta"]]
)

# Preprocesador
preprocesador = ColumnTransformer(
    transformers=[
        (
            "litologia",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            variable_litologia
        ),
        (
            "pirita",
            codificador_pirita,
            variable_pirita
        ),
        (
            "numericas",
            "passthrough",
            variables_numericas
        )
    ]
)

print("Preprocesador creado correctamente.")

Preprocesador creado correctamente.

In [13]:
X_train_procesado = preprocesador.fit_transform(X_train)

X_test_procesado = preprocesador.transform(X_test)

print("X_train original:", X_train.shape)
print("X_train procesado:", X_train_procesado.shape)

print("\nX_test original:", X_test.shape)
print("X_test procesado:", X_test_procesado.shape)

X_train original: (240, 10)
X_train procesado: (240, 24)

X_test original: (60, 10)
X_test procesado: (60, 24)

In [14]:
from sklearn.ensemble import RandomForestRegressor

# Crear el modelo
modelo_rf = RandomForestRegressor(
    n_estimators=300,
    random_state=2026,
    n_jobs=-1
)

# Entrenar el modelo
modelo_rf.fit(
    X_train_procesado,
    y_train
)

print("Random Forest entrenado correctamente.")
print("Número de árboles:", modelo_rf.n_estimators)
print("Muestras utilizadas para entrenamiento:", X_train_procesado.shape[0])
print("Variables utilizadas por el modelo:", X_train_procesado.shape[1])

Random Forest entrenado correctamente.
Número de árboles: 300
Muestras utilizadas para entrenamiento: 240
Variables utilizadas por el modelo: 24

In [15]:
y_pred = modelo_rf.predict(X_test_procesado)

print("Predicciones realizadas correctamente.")
print("Número de predicciones:", len(y_pred))

print("\nPrimeros 10 IPE predichos:")
print(y_pred[:10])

Predicciones realizadas correctamente.
Número de predicciones: 60

Primeros 10 IPE predichos:
[36.35933333 45.34333333 38.09666667 42.62233333 36.192      39.35766667
 38.58833333 39.22566667 50.31833333 45.69033333]

In [16]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

# Calcular métricas
mae = mean_absolute_error(y_test, y_pred)

rmse = np.sqrt(
    mean_squared_error(y_test, y_pred)
)

r2 = r2_score(y_test, y_pred)

print("EVALUACIÓN DEL MODELO")
print("---------------------")
print("MAE :", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R²  :", round(r2, 4))

EVALUACIÓN DEL MODELO
---------------------
MAE : 3.16
RMSE: 4.1
R²  : 0.7399

In [17]:
comparacion = pd.DataFrame({
    "IPE_REAL": y_test.values,
    "IPE_PREDICHO": y_pred
})

comparacion["ERROR"] = (
    comparacion["IPE_REAL"] -
    comparacion["IPE_PREDICHO"]
)

comparacion["ERROR_ABS"] = comparacion["ERROR"].abs()

comparacion.head(10)

   IPE_REAL  IPE_PREDICHO     ERROR  ERROR_ABS
0      35.6     36.359333 -0.759333   0.759333
1      43.1     45.343333 -2.243333   2.243333
2      42.5     38.096667  4.403333   4.403333
3      40.7     42.622333 -1.922333   1.922333
4      43.4     36.192000  7.208000   7.208000
5      32.1     39.357667 -7.257667   7.257667
6      37.0     38.588333 -1.588333   1.588333
7      44.8     39.225667  5.574333   5.574333
8      48.8     50.318333 -1.518333   1.518333
9      39.4     45.690333 -6.290333   6.290333

In [18]:
# Obtener nombres de las variables después del preprocesamiento
nombres_variables = preprocesador.get_feature_names_out()

print("Número de variables:", len(nombres_variables))

for variable in nombres_variables:
    print(variable)

Número de variables: 24
litologia__LITOLOGIA_Arcillolita
litologia__LITOLOGIA_Arcillolita con pirita
litologia__LITOLOGIA_Brecha hidrotermal calcita-pirita
litologia__LITOLOGIA_Caliza bioclastica
litologia__LITOLOGIA_Caliza micritica
litologia__LITOLOGIA_Cuarzoarenita
litologia__LITOLOGIA_Limolita micacea
litologia__LITOLOGIA_Lodolita albitizada
litologia__LITOLOGIA_Lodolita calcarea
litologia__LITOLOGIA_Lodolita carbonosa
litologia__LITOLOGIA_Lodolita oscura
litologia__LITOLOGIA_Lutita negra
litologia__LITOLOGIA_Micrita
litologia__LITOLOGIA_Micrita negra
litologia__LITOLOGIA_Shale
pirita__GUIA_PIRITA
numericas__DIST_FALLA_m
numericas__DIST_INTERSECCION_m
numericas__Na_pct
numericas__K_pct
numericas__CR_ppm
numericas__V_ppm
numericas__K_Na
numericas__Be_ppm

In [19]:
# Obtener importancia de cada variable
importancias = modelo_rf.feature_importances_

importancia_df = pd.DataFrame({
    "VARIABLE": nombres_variables,
    "IMPORTANCIA": importancias
})

# Ordenar de mayor a menor
importancia_df = importancia_df.sort_values(
    by="IMPORTANCIA",
    ascending=False
)

# Convertir a porcentaje
importancia_df["IMPORTANCIA_PCT"] = (
    importancia_df["IMPORTANCIA"] * 100
)

importancia_df.head(15)

                                  VARIABLE  IMPORTANCIA  IMPORTANCIA_PCT
17          numericas__DIST_INTERSECCION_m     0.472315        47.231532
22                         numericas__K_Na     0.111340        11.134000
18                       numericas__Na_pct     0.063780         6.378050
21                        numericas__V_ppm     0.062819         6.281941
6    litologia__LITOLOGIA_Limolita micacea     0.059218         5.921760
20                       numericas__CR_ppm     0.046352         4.635247
19                        numericas__K_pct     0.037246         3.724610
23                       numericas__Be_ppm     0.035511         3.551133
16                 numericas__DIST_FALLA_m     0.033172         3.317191
0         litologia__LITOLOGIA_Arcillolita     0.018625         1.862456
15                     pirita__GUIA_PIRITA     0.014455         1.445501
5       litologia__LITOLOGIA_Cuarzoarenita     0.014446         1.444590
8   litologia__LITOLOGIA_Lodolita calcarea     0.012310         1.230999
11       litologia__LITOLOGIA_Lutita negra     0.006374         0.637429
14              litologia__LITOLOGIA_Shale     0.001967         0.196659

In [20]:
# Crear copia para agrupar importancias
importancia_agrupada = importancia_df.copy()

def obtener_parametro(nombre):
    
    if nombre.startswith("litologia__"):
        return "LITOLOGIA"
    
    elif nombre.startswith("pirita__"):
        return "GUIA_PIRITA"
    
    elif nombre.startswith("numericas__"):
        return nombre.replace("numericas__", "")
    
    else:
        return nombre

importancia_agrupada["PARAMETRO"] = (
    importancia_agrupada["VARIABLE"].apply(obtener_parametro)
)

# Sumar importancias de categorías que pertenecen al mismo parámetro
importancia_parametros = (
    importancia_agrupada
    .groupby("PARAMETRO", as_index=False)["IMPORTANCIA"]
    .sum()
)

# Convertir a porcentaje
importancia_parametros["IMPORTANCIA_PCT"] = (
    importancia_parametros["IMPORTANCIA"] * 100
)

# Ordenar
importancia_parametros = importancia_parametros.sort_values(
    by="IMPORTANCIA_PCT",
    ascending=False
)

importancia_parametros

             PARAMETRO  IMPORTANCIA  IMPORTANCIA_PCT
3  DIST_INTERSECCION_m     0.472315        47.231532
7            LITOLOGIA     0.123008        12.300798
5                 K_Na     0.111340        11.134000
8               Na_pct     0.063780         6.378050
9                V_ppm     0.062819         6.281941
1               CR_ppm     0.046352         4.635247
6                K_pct     0.037246         3.724610
0               Be_ppm     0.035511         3.551133
2         DIST_FALLA_m     0.033172         3.317191
4          GUIA_PIRITA     0.014455         1.445501

In [21]:
# Recuperar las 60 muestras originales utilizadas como prueba
resultados_60 = df.loc[X_test.index].copy()

# Agregar el IPE calculado por el modelo
resultados_60["IPE_ML"] = y_pred

# Calcular diferencia entre IPE original e IPE del modelo
resultados_60["ERROR_ML"] = (
    resultados_60["IPE"] - resultados_60["IPE_ML"]
)

resultados_60["ERROR_ABS_ML"] = (
    resultados_60["ERROR_ML"].abs()
)

print("Número de muestras:", len(resultados_60))

resultados_60[
    [
        "ID_MUESTRA",
        "LATITUD",
        "LONGITUD",
        "IPE",
        "IPE_ML",
        "ERROR_ML",
        "ERROR_ABS_ML"
    ]
].head(10)

Número de muestras: 60

    ID_MUESTRA   LATITUD   LONGITUD   IPE     IPE_ML  ERROR_ML  ERROR_ABS_ML
224   MUZO_225  5.488711 -74.135454  35.6  36.359333 -0.759333      0.759333
200   MUZO_201  5.491938 -74.035630  43.1  45.343333 -2.243333      2.243333
247   MUZO_248  5.554891 -74.125877  42.5  38.096667  4.403333      4.403333
134   MUZO_135  5.529205 -74.066612  40.7  42.622333 -1.922333      1.922333
144   MUZO_145  5.560212 -74.108996  43.4  36.192000  7.208000      7.208000
294   MUZO_295  5.506219 -74.030444  32.1  39.357667 -7.257667      7.257667
287   MUZO_288  5.497559 -74.029441  37.0  38.588333 -1.588333      1.588333
225   MUZO_226  5.479838 -74.040905  44.8  39.225667  5.574333      5.574333
131   MUZO_132  5.518089 -74.070448  48.8  50.318333 -1.518333      1.518333
191   MUZO_192  5.485131 -74.094246  39.4  45.690333 -6.290333      6.290333

In [22]:
import os

# Carpeta donde está el CSV original
carpeta_salida = os.path.dirname(archivo)

# Nombre del nuevo archivo
ruta_salida = os.path.join(
    carpeta_salida,
    "Esmeraldina_ML_60_Muestras_Prueba.csv"
)

# Exportar
resultados_60.to_csv(
    ruta_salida,
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

print("CSV creado correctamente:")
print(ruta_salida)

CSV creado correctamente:
C:\Users\perey\OneDrive - Esri Colombia, Ecuador y Panamá\Esmeraldina\Fase IV. Machine Learning\Esmeraldina-ArcGISPro\CSV'S\Esmeraldina_ML_60_Muestras_Prueba.csv

In [23]:
from sklearn.pipeline import Pipeline

esmeraldina = Pipeline(
    steps=[
        ("preprocesador", preprocesador),
        ("random_forest", modelo_rf)
    ]
)

print("Esmeraldina V1 preparada correctamente.")

Esmeraldina V1 preparada correctamente.

In [24]:
# Predicción usando Esmeraldina completa
prueba_esmeraldina = esmeraldina.predict(X_test)

# Comprobar que produce los mismos resultados
diferencia_maxima = abs(prueba_esmeraldina - y_pred).max()

print("Diferencia máxima:", diferencia_maxima)

if diferencia_maxima < 0.000001:
    print("Esmeraldina funciona correctamente.")
else:
    print("Revisar el modelo antes de guardarlo.")

Diferencia máxima: 2.1316282072803006e-14
Esmeraldina funciona correctamente.

In [25]:
import joblib
import os

# Crear una carpeta para los modelos
carpeta_modelo = os.path.join(
    os.path.dirname(archivo),
    "Modelos"
)

os.makedirs(
    carpeta_modelo,
    exist_ok=True
)

# Ruta del modelo
ruta_modelo = os.path.join(
    carpeta_modelo,
    "Esmeraldina_RF_V1.joblib"
)

# Información que guardaremos
paquete_esmeraldina = {
    "modelo": esmeraldina,
    "columnas_X": columnas_X,
    "version": "Esmeraldina_RF_V1",
    "algoritmo": "RandomForestRegressor",
    "n_estimators": 300,
    "random_state": 2026,
    "MAE_test": mae,
    "RMSE_test": rmse,
    "R2_test": r2
}

# Guardar
joblib.dump(
    paquete_esmeraldina,
    ruta_modelo
)

print("ESMERALDINA GUARDADA CORRECTAMENTE")
print("----------------------------------")
print("Ruta:")
print(ruta_modelo)

ESMERALDINA GUARDADA CORRECTAMENTE
----------------------------------
Ruta:
C:\Users\perey\OneDrive - Esri Colombia, Ecuador y Panamá\Esmeraldina\Fase IV. Machine Learning\Esmeraldina-ArcGISPro\CSV'S\Modelos\Esmeraldina_RF_V1.joblib

In [26]:
import joblib

ruta_modelo = r"C:\Users\perey\OneDrive - Esri Colombia, Ecuador y Panamá\Esmeraldina\Fase IV. Machine Learning\Esmeraldina-ArcGISPro\Modelos\Esmeraldina_RF_V1.joblib"

# Cargar el paquete completo
esmeraldina_cargada = joblib.load(ruta_modelo)

# Extraer el modelo
modelo_cargado = esmeraldina_cargada["modelo"]

print("Modelo cargado correctamente.")
print("Versión:", esmeraldina_cargada["version"])
print("Algoritmo:", esmeraldina_cargada["algoritmo"])

print("\nVariables que espera Esmeraldina:")
print(esmeraldina_cargada["columnas_X"])

Modelo cargado correctamente.
Versión: Esmeraldina_RF_V1
Algoritmo: RandomForestRegressor

Variables que espera Esmeraldina:
['LITOLOGIA', 'DIST_FALLA_m', 'DIST_INTERSECCION_m', 'GUIA_PIRITA', 'Na_pct', 'K_pct', 'CR_ppm', 'V_ppm', 'K_Na', 'Be_ppm']

In [27]:
prediccion_prueba = modelo_cargado.predict(
    X_test.head(5)
)

print("Predicciones de prueba:")

for i, prediccion in enumerate(prediccion_prueba, start=1):
    print(f"Muestra {i}: IPE_ML = {prediccion:.2f}")

Predicciones de prueba:
Muestra 1: IPE_ML = 36.36
Muestra 2: IPE_ML = 45.34
Muestra 3: IPE_ML = 38.10
Muestra 4: IPE_ML = 42.62
Muestra 5: IPE_ML = 36.19

In [28]:
print("INFORMACIÓN DE ESMERALDINA")
print("--------------------------")

print("Versión:", esmeraldina_cargada["version"])
print("Algoritmo:", esmeraldina_cargada["algoritmo"])
print("Número de árboles:", esmeraldina_cargada["n_estimators"])
print("Random state:", esmeraldina_cargada["random_state"])

print("\nMÉTRICAS DE VALIDACIÓN")
print("MAE :", round(esmeraldina_cargada["MAE_test"], 2))
print("RMSE:", round(esmeraldina_cargada["RMSE_test"], 2))
print("R²  :", round(esmeraldina_cargada["R2_test"], 4))

INFORMACIÓN DE ESMERALDINA
--------------------------
Versión: Esmeraldina_RF_V1
Algoritmo: RandomForestRegressor
Número de árboles: 300
Random state: 2026

MÉTRICAS DE VALIDACIÓN
MAE : 3.16
RMSE: 4.1
R²  : 0.7399